version: "3.9"

services:
  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/mysite/assets/:ro
    ports:
      - "80:80"
    depends_on:
      - django
  django:
    build: .
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput 
      && uwsgi --ini mysite.uwsgi.ini"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/code/media/
      - web_static:/var/www/mysite/assets/
      - .:/code
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  uwsgi_data:
  web_static: