version: "3.8"


services:
  web:
    build: .
    command: gunicorn eCommerce2022.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: